site_name: Chojo - Dev Blog and Portfolio
site_url: https://chojo.dev/
site_description: Welcome to my website. You can find information about my projects and myself here or dive into my blog
repo_url: https://github.com/rainbowdashlabs/chojodev/
copyright: Chojo 2023
repo_name: chojo.dev
docs_dir: docs
site_dir: site
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - blog:
      blog_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: -1  # -1 for full content
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Europe/Berlin

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - 'About me':
      - about_me/index.md
      - 'My Story': about_me/my_story.md
      - 'Milestones': about_me/milestones.md
      - 'Technologies': about_me/technologies.md
  - 'Minecraft':
      - minecraft/index.md
      - 'Eldoria': minecraft/eldoria.md
      - 'Big Doors Opener': minecraft/big_doors_opener.md
      - 'Blood Night': minecraft/blood_night.md
      - 'Companies': minecraft/companies.md
      - 'Schematic Brush Reborn':
        - minecraft/schematic_brush_reborn/index.md
        - 'Grid Selector': minecraft/schematic_brush_reborn/grid_selector.md
        - 'Survival Schematic Brush': minecraft/schematic_brush_reborn/survival_schematic_brush.md
        - 'Schematic Tools': minecraft/schematic_brush_reborn/schematic_tools.md
        - 'Schematic Brush Database': minecraft/schematic_brush_reborn/schematic_brush_database.md
  - 'Discord':
      - discord/index.md
      - 'Reputation Bot': discord/reputation_bot.md
      - 'Lyna': discord/lyna.md
  - 'Libraries':
      - libraries/index.md
      - 'SADU': libraries/sadu.md
      - 'Universalis Java': libraries/universalis_java.md
      - 'Jackson Bukkit': libraries/jackson_bukkit.md
  - 'More':
      - more/index.md
      - 'Sql Java Tutorial': more/sql_java.md

theme:
  logo: assets/images/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.indexes
    - navigation.top
    - content.code.annotate
    - navigation.indexes
    - toc.follow
    - content.code.copy
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Emoji search
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/


extra:
  social:
    - name: Mastodon@chaos.social
      icon: fontawesome/brands/mastodon
      link: https://chaos.social/@chojo
    - name: Patreon
      icon: fontawesome/brands/patreon
      link: https://www.patreon.com/eldoriaplugins
    - name: Spigot
      icon: material/minecraft
      link: https://www.spigotmc.org/resources/authors/585216/
    - name: Github
      icon: fontawesome/brands/github
      link: https://github.com/rainbowdashlabs
    - name: Discord
      icon: fontawesome/brands/discord
      link: https://discord.chojo.dev
    - name: Blog RSS
      icon: fontawesome/solid/rss
      link: https://chojo.dev/feed_rss_created.xml
